
services:
   
   temperature_pub:

    build: 
      context: ./packages
      dockerfile: temperature_pub/Dockerfile

    environment:
      # Note ROS_LOCALHOST_ONLY should be changed to 0 if we change the network to bridge
      - ROS_LOCALHOST_ONLY=1
      # For Linux : (IDs 0-101 and 215-232)
      - ROS_DOMAIN_ID=42

    network_mode: host

    # Enables the RMW (FastDDS) to use shared memory
    ipc: host 

    container_name: temperature_publisher

   temperature_sub:

    build: 
      context: ./packages
      dockerfile: temperature_sub/Dockerfile

    environment:
      - ROS_LOCALHOST_ONLY=1
      - ROS_DOMAIN_ID=42

    network_mode: host
    ipc: host

    container_name: temperature_subscriber
    
    depends_on:
      - temperature_pub 